services:
  api:
    build:
      context: .
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    command: flask run
    depends_on:
      - db
      - redis
  celery:
    env_file:
      - .env
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A server.celery_config worker -l info
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
